services:
  dotnet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5069
      - ASPNETCORE_HTTPS_PORTS=7220
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/prueba.pfx #quizas luego tengo que poner el cert en la carpeta https
    container_name: dotnet.api
    # image: dotnet.api
    build:
      context: .
      dockerfile: /PruebaApiRest/Dockerfile
    ports:
      - "5069:5069"
      - "7220:7220"
    volumes:
      - ~/.aspnet/https:/https:ro
        
  react.client:
    build:
      context: ./frontreact
      dockerfile: /Dockerfile
    container_name: react.client
    ports:
      - "55205:55205"
    volumes:
      - ./frontreact:/app  
      - /app/node_modules  
    depends_on: 
      - dotnet.api