FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app

EXPOSE 5069
EXPOSE 7220

RUN mkdir -p /app/data  # Crear la carpeta para SQLite

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Development
WORKDIR /src

COPY ["PruebaApiRest/ApiREST- .NET.csproj", "PruebaApiRest/"]

RUN dotnet restore "PruebaApiRest/ApiREST- .NET.csproj"

COPY . .

WORKDIR "/src/PruebaApiRest"
RUN dotnet build "ApiREST- .NET.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Development
RUN dotnet publish "ApiREST- .NET.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

run dotnet dev-certs https


ENTRYPOINT ["dotnet", "ApiREST- .NET.dll"]